### ISSUE TITLE
Building the iso fails at stage 1

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/lunar-iso#27]
I wanted to build an iso myself. But it fails at:

```
Creating /var/log/lunar/compile/timezone-data-2016i.xz 
Creating /var/log/lunar/install/timezone-data-2016i
Creating /var/log/lunar/md5sum/timezone-data-2016i
Creating /var/cache/lunar/timezone-data-2016i-x86_64-pc-linux-gnu.tar.xz

mv: cannot stat '/var/lock/installing.12754': No such file or directory
make: *** [mkfiles/stage1.mk:34: /home/mwgrient/lunar-iso/BUILD/.stage1-toolchain] Error 1
root@tulp /home/mwgrient/lunar-iso #
```

Regards, Marco

**Comment by Ratler** [comment]
The error most likely occurred much earlier. Without more to go on it's impossible to tell what went wrong. I have some uncommitted changes coming soon that might correct any issues encountered now. I successfully built stage 1 last weekend, some issues remain due to some recent changes with stage 2 however.

**Comment by mwgrient** [comment]
I will wait for the changes then. Thanks.
